import test from 'node:test';import assert from 'node:assert/strict';
import { createDisplacementMap, displacementKey, normalizedMapOptions, roundedRectDistance, clamp, smoothUnion } from '../../packages/core/dist/geometry.js';
import { getDisplacementTexture, getGlassDiagnostics, clearGlassCache, supportsSvgBackdrop } from '../../packages/core/dist/browser.js';
const sample=(m,x,y)=>Array.from(m.data.slice((y*m.width+x)*4,(y*m.width+x)*4+4));
test('SDF center is inside',()=>assert(roundedRectDistance(50,25,100,50,12)<0));
test('SDF straight boundary is zero',()=>assert.equal(roundedRectDistance(0,25,100,50,12),0));
test('rounded corner is outside',()=>assert(roundedRectDistance(0,0,100,50,12)>0));
test('SDF symmetric horizontally',()=>assert.equal(roundedRectDistance(4,18,100,50,12),roundedRectDistance(96,18,100,50,12)));
test('clamp bounds values',()=>{assert.equal(clamp(-4,0,2),0);assert.equal(clamp(8,0,2),2);});
test('neutral center uses 128, not black',()=>assert.deepEqual(sample(createDisplacementMap({width:100,height:60}),50,30),[128,128,128,255]));
test('left and right edge vectors have opposite signs',()=>{const m=createDisplacementMap({width:100,height:60});assert(sample(m,1,30)[0]<128);assert(sample(m,98,30)[0]>128);});
test('top and bottom use green displacement',()=>{const m=createDisplacementMap({width:100,height:60});assert(sample(m,50,1)[1]<128);assert(sample(m,50,58)[1]>128);});
test('outside rounded corner stays neutral',()=>assert.deepEqual(sample(createDisplacementMap({width:100,height:60,radius:24}),0,0),[128,128,128,255]));
test('pixels all opaque; RG stays byte encoded',()=>{const m=createDisplacementMap({width:45,height:37});for(let i=0;i<m.data.length;i+=4){assert.equal(m.data[i+3],255);assert.equal(m.data[i+2],128);assert(m.data[i]>=0&&m.data[i]<=255);}});
test('high resolution respects area cap',()=>{const m=createDisplacementMap({width:12000,height:12000,maxResolution:512});assert(m.width*m.height<=131072);assert(m.width<=512);});
test('long thin texture respects side cap',()=>{const m=createDisplacementMap({width:16000,height:2,maxResolution:99999});assert(m.width<=512);assert(m.height>=1);});
test('tiny dimensions produce a valid pixel',()=>assert.equal(createDisplacementMap({width:.01,height:.01}).data.length,4));
test('negative radius clamps to zero',()=>assert.equal(normalizedMapOptions({width:20,height:40,radius:-1}).radius,0));
test('radius cannot exceed half shortest side',()=>assert.equal(normalizedMapOptions({width:20,height:40,radius:100}).radius,10));
test('equivalent rounded sizes share key',()=>assert.equal(displacementKey({width:100.01,height:60}),displacementKey({width:100.1,height:60})));
test('distinct geometric profiles use distinct keys',()=>assert.notEqual(displacementKey({width:100,height:60,edge:8}),displacementKey({width:100,height:60,edge:16})));
for(const value of [0,-1,NaN,Infinity,1e308])test(`invalid dimensions rejected: ${value}`,()=>assert.throws(()=>createDisplacementMap({width:value,height:20}),RangeError));
test('nonfinite edge rejected',()=>assert.throws(()=>createDisplacementMap({width:20,height:20,edge:NaN}),RangeError));
test('module loads without DOM; browser helpers safely decline',()=>{assert.equal(typeof globalThis.document,'undefined');assert.equal(getDisplacementTexture({width:20,height:20}),null);assert.equal(supportsSvgBackdrop(),false);clearGlassCache();assert.equal(getGlassDiagnostics().entries,0);});
test('smooth union without blend is the hard union',()=>{assert.equal(smoothUnion(3,-2,0),-2);assert.equal(smoothUnion(3,-2,-1),-2);});
test('smooth union is symmetric',()=>assert.equal(smoothUnion(2,-5,4),smoothUnion(-5,2,4)));
test('smooth union never exceeds the hard union',()=>{for(let a=-20;a<=20;a+=1.5)for(let b=-20;b<=20;b+=1.5)assert(smoothUnion(a,b,6)<=Math.min(a,b)+1e-9);});
test('smooth union bulges by at most k/4',()=>{for(let a=-20;a<=20;a+=1.5)for(let b=-20;b<=20;b+=1.5)assert(smoothUnion(a,b,6)>=Math.min(a,b)-6/4-1e-9);});
test('equal distances bulge by exactly k/4',()=>assert.equal(smoothUnion(-3,-3,8),-3-2));
test('shapes further apart than the blend radius are untouched',()=>assert.equal(smoothUnion(0,40,6),Math.min(0,40)));
test('smooth union rejects non-finite distances',()=>{assert.throws(()=>smoothUnion(NaN,1,4),RangeError);assert.throws(()=>smoothUnion(1,Infinity,4),RangeError);});
